name = "PublicGoodsTournement"
uuid = "0f0a6ae1-6fda-43cd-a599-6a93ebc0c6a6"
authors = ["itsdfish <itsdfish@gmail.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
